<?php

/**
 * ProcessWire simple Partial Renderer
 *
 * Renders partial templates in a "framework" fashion
 *
 * TemplatePartialRenderer modulo for ProcessWire 2.4
 * Copyright (C) 2010 by Maks Feltrin - pine3ree
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 *
 */

class TemplatePartialRenderer extends WireData implements Module
{
    public static function getModuleInfo()
    {
        return array(
            'title'    => 'Template Partial Renderer',
            'version'  => 100,
            'summary'  => 'Render a partial php template injecting variables through an array',
            'href'     => 'https://github.com/pine3ree/TemplatePartialRenderer',
            'singular' => true,
            'autoload' => true,
        );
    }

    public function init()
    {
        $this->addHook('Page::renderPartial', $this, 'renderPartial');
    }

    public function renderPartial($event)
    {
        $out = '';

        $tmpl = $event->arguments(0);
        if (!is_string($tmpl)) {
            if ($this->config->debug) {
                throw new WireException('The template argument must be a string');
            }

            return;
        };

        $data = $event->arguments(1) ? $event->arguments(1) : array();
        if (!is_array($data)) {
            if ($this->config->debug) {
                throw new WireException(
                    'The second argument must be an array of variables to inject into the template or NULL'
                );
            }

            return;
        };

        $echo = (bool) $event->arguments(2);

        if (!in_array(substr($tmpl, -4), array('.php', '.tpl', '.inc', 'phtml'))) {
            $tmpl = $tmpl . '.php';
        }

        $file = $this->config->paths->templates . $tmpl;

        if (is_file($file)) {
            extract($data);

            ob_start();
            include $file;
            $out = ob_get_contents();
            ob_end_clean();
        } else {
            if ($this->config->debug) {
                throw new WireException(sprintf(
                    'The requested template file "%s" was not found or is nt readable',
                    $file
                ));
            }

            return;
        }

        if ($echo) {
            echo $out;
            return;
        }

        return $out;
    }
}
